### ISSUE TITLE
maio-iOS-SDKに関する質問

### ISSUE THREAD

**Issue by alertross** [imobile-maio/maio-iOS-SDK#1]
1.MaioFailReasonVideoPlayback　このミスの詳しく原因はなんですか？一体どんな原因で起こりますか？

2.私は(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptionsで     [Maio startWithMediaId:MAIO_MEDIA_ID delegate:self];を初期化しました。しかし、ある時間で [Maio canShow]を使うと、maioのデリゲートでミスがないですが、広告はダウンロードできません。その原因は(void)maioDidFail:(NSString *)zoneId reason:(MaioFailReason)reason がcallBackしませんでした。どうしてこの問題を起こしますか？

                                                            できるだけ早めに返事してください。

**Comment by im-kashi** [comment]
返信が遅くなり申し訳ありません。。

> 1.MaioFailReasonVideoPlayback　このミスの詳しく原因はなんですか？

動画広告の再生中に予期しないエラーが生じ、再生が続けられなくなった事を示唆しています。
基本的には起こらないはずですが、何らかの理由により動画ファイルが破損したりした場合には起こる可能性はあります。

> 2.

[Maio canShow] は動画広告の再生準備が整っているかどうかを示す BOOL 値を返します。
このメソッドが NO を返す理由は、
- 広告リソースのダウンロード中。
- 広告案件側の再生キャップ制限中。

等が考えられます。

この挙動は仕様通りですので、[MaioDelegate maioDidFail:reason] はコールバックされません。
[MaioDelegate maioDidFail:reason] がコールバックされるのは、ネットワークエラーや予期しない内部エラーが発生した時等に限られます。

**Comment by alertross** [comment]
ありがとう
