### ISSUE TITLE
iOS 14 SKAdNetworkに関する質問

### ISSUE THREAD

**Issue by yasuradodo** [imobile-maio/maio-iOS-SDK#49]
iOS14のSKAdNetworkに対応するためにinfo.plistに全ての広告ネットワークのSKAdNetworkIdentifierを追加しています。
御社のSKAdNetworkIdentifierの記載が見つからないのですが、何を利用すれば良いのでしょうか？
よろしくお願いします。

**Comment by im-ade** [comment]
@yasuradodo 

The SKAdNetworkIdentifier for maio is:

v4nxqhlyqp.skadnetwork

and can be added like below:

```
<key>SKAdNetworkItems</key>
    <array>
        <dict>
            <key>SKAdNetworkIdentifier</key>
            <string>v4nxqhlyqp.skadnetwork</string>
        </dict>
    </array>
```

Thanks.

よろしくお願いします。

**Comment by yasuradodo** [comment]
Thank you.
