### ISSUE TITLE
動画消える状況に関して

### ISSUE THREAD

**Issue by beikin** [imobile-maio/maio-iOS-SDK#6]
こんにちわ
今、Maio（バージョン：1.2.4）のフレームワークを使っています、
動画を表示する時、いきなり消えました、その現象を起きた原因を教えてもらえますか？

あと、[Maio canShow]でYESを返したけど、実際に放送できないって
ケースがありますか？
早速ご返信下さい。

**Comment by im-ttmskk** [comment]
> 動画を表示する時、いきなり消えました、その現象を起きた原因を教えてもらえますか？

動画を再生する際、何か異常（動画ファイルや、エンドカードの破損など）があった場合に、キャンセルするようになっています。
このとき、エラーとして`[MaioDelegate maioDidFail:reason:]`に、`MaioFailReazonVideoPlayback`を通知します。

> あと、[Maio canShow]でYESを返したけど、実際に放送できないってケースがありますか？

仕様上はありませんが、上記のような不具合によって発生する場合があります。

**Comment by beikin** [comment]
返信、ありがとうございます
